config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'users#show'

  resources :users
  resources :providers
  resources :products
  resources :pricebook_entries
  resources :clients
  resources :contracts
  resources :orders
  resources :order_items
  resources :events

end

app/models/user.rb
class User < Account
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :find_user, only: [:new, :create]

  def new
    @user = User.new
    # enter new email address
  end

  def create
    if params[:isrando] == '1'
      @user = Provider.create(
        firstname:    Faker::Name.first_name,
        lastname:     Faker::Name.last_name,
        personemail:  Faker::Internet.email,
        recordtypeid: '012700000009miG'
      )
    else
      @user = Provider.find_by_personemail params[:user][:personemail]
    end
    # swap user
    session[:user] = @user.personemail
    redirect_to root_path
  end

  def show
  end
end

app/views/users/_manage_rate.html.haml
- if @user.product.present?
  - if @user.unitprice == nil
    .span
      = link_to 'Set up Rate', new_pricebook_entry_path
    .span
      %small Create standard pricebook entry for service provider, stores default list price (hourly rate)
  - else
    .span
      %strong Default Rate #{number_to_currency @user.unitprice}
    .span
      %small
        = link_to 'Change Default Rate', edit_pricebook_entry_path(@user.product.pricebook_entries.last)
    
- else
  .span
    = link_to 'Request to become an Improve Trainer', products_path, method: :post 
  .span
    %small Create 'sku' for service provider 

app/views/users/index.html.haml
Hello
= @user.name

- unless @user.pricebook_entry.present?
  become an improve trainer
  = link_to 'Set Price to $55.00*', products_path, method: :post
- else
  ready to help your clients improve?
  = link_to 'Add new Client', new_client_path

  %h3 Client List
  %ul
    - @user.contracts.each do |contract|
      %li=link_to contract.client.name, client_path(contract.client, contract: contract.sfid)

app/views/users/new.html.haml
Choose your user you boozer:
= form_for @user do |f|
  .span
    = f.label :email
    = f.text_field :personemail
  .span
    = label_tag :make_random_user
    = check_box_tag :isrando
  .span
    = f.submit 'Enable God Mode'
%p
= link_to 'Click Here to Learn How Uber Uses God Mode', 'http://www.forbes.com/sites/kashmirhill/2014/10/03/god-view-uber-allegedly-stalked-users-for-party-goers-viewing-pleasure/', target: :blank

app/views/users/show.html.haml
%h3 Hello #{@user.name}
= render 'manage_rate'
%br
- unless @user.unitprice == nil
  .span
    Ready to help your clients improve?
    = link_to 'Add new Client', new_client_path
    .span
      %small Creates client account and creates an open order with current user, used to attach Order Items (amount and sessions).
  %h3 Current Client List
  %ul
    - @user.orders.each do |order|
      %li=link_to order.client.name, order_path(order)