config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'users#show'

  resources :users
  resources :providers
  resources :products
  resources :pricebook_entries
  resources :clients
  resources :contracts
  resources :orders
  resources :order_items
  resources :events

end

app/models/order.rb
class Order < ActiveRecord::Base
  self.table_name = 'heroku.order'
  belongs_to :client, primary_key: 'personcontactid', foreign_key: 'customerauthorizedbyid'
  belongs_to :provider, primary_key: 'sfid', foreign_key: 'accountid'

  belongs_to :pricebook, primary_key: 'sfid', foreign_key: 'pricebook2id'
  has_many :order_items, primary_key: 'sfid', foreign_key: 'orderid'
  has_many :events, primary_key: 'sfid', foreign_key: 'whatid'

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create 
    pricebook = Pricebook.find_by_name 'Standard Price Book'
    @contract = Contract.find params[:contract]

    # re: @client.contracts.last just turn current clients resource into contracts resource
    @order = Order.create(
      accountid: @user.sfid,
      # contractid: @contract.sfid, 
      pricebook2id: pricebook.sfid,
      effectivedate: Date.today,
      status: 'Draft'
    )

    redirect_to @order
  end

  def show
    @order = Order.find params[:id]
  end

  def update

    @order = Order.find params[:id]
    pricebook_entry = PricebookEntry.find_by_sfid @user.pricebook_entry.sfid

    # Quantity and Cost
    OrderItem.create(
      orderid: @order.sfid,
      pricebookentryid: pricebook_entry.sfid,
      quantity: 10,
      listprice: params[:unit_price] || pricebook_entry.unitprice,
      unitprice: params[:unit_price] || pricebook_entry.unitprice

    )
    # quantity not required
    redirect_to @order
  end
end

app/views/orders/show.html.haml
/ render 'add_order_item_form' if @order.order_items.empty?
- if @order.order_items.empty?
  .span
    Current Order is empty. Add an amount to Order #{@order.ordernumber}.
  .span
    Pricing: #{@order.pricebook.name}
  = form_for OrderItem.new do |f|
    / make form param to add in unit price
    / default input #{@user.unitprice}
    .span
      = f.label :number_of_sessions
    .span
      = f.number_field :quantity, value: 10
    .span
      = f.label :price_per_session
    .span
      = f.number_field :unitprice, value: @user.unitprice
    = f.hidden_field(:orderid, value: @order.sfid)
    = f.hidden_field(:pricebookentryid, value: @user.product.pricebook_entries.last.sfid)
    = f.submit 'Add Order Item'
%h3 Order History
Bring us the girl and wipeaway the debt for #{@order.client.name}.
/ SF calculated fields can take up to 10 min to sync back down, unless on streaming api
/ likely won't want to depend on those fields for immediate view presentation
- if @order.order_items.any?
  .span
    / requires a delay to work..to update available quantity. could just add with create sync?
    = number_to_currency (@order.order_items.last.unitprice * @order.order_items.last.availablequantity)
  .span
    = link_to 'Add Session', events_path(order: @order.sfid), method: :post # new_event_path(order: @order.sfid)
  %h4 Events
  - @order.events.each do |event|
    %h5 #{event.subject}
    = event.starts
    = event.durationinminutes 
    Minutes
= link_to 'Back', root_path